'use strict';
const reviewNote=document.createElement('label');reviewNote.className='demo-note';reviewNote.innerHTML='REVISION NOTE (OPTIONAL)<textarea id="demoRevisionNote" placeholder="Try: make the primary action clearer and check the mobile reading order."></textarea>';
document.querySelector('.preview-lane-deck').after(reviewNote);
const quick=document.createElement('div');quick.className='demo-quick-links';quick.innerHTML='<button id="demoOpenOpportunities">OPEN OPPORTUNITIES & PROPOSALS</button><button id="demoOpenInvoices">VIEW PROJECTS & INVOICES</button>';document.querySelector('.agency-hero').append(quick);
function revealRevenue(){showView('command');document.querySelector('#revenueDesk').scrollIntoView({block:'start',behavior:'smooth'})}
$('#demoRevenue').addEventListener('click',revealRevenue);$('#demoOpenOpportunities').addEventListener('click',revealRevenue);
$('#demoOpenInvoices').addEventListener('click',()=>document.querySelector('#projectLedger').scrollIntoView({block:'center',behavior:'smooth'}));
$('#demoMission').addEventListener('click',()=>{showView('command');$('#missionText').value='Design a responsive landing page for a fictional neighborhood creative studio. Include audience research, Figma UX, Adobe creative direction, engineering and independent review.';$('#project').value='NORTHSTAR · SAMPLE PROJECT';$('#missionCount').textContent=$('#missionText').value.length;$('#missionText').focus();$('#commandDesk').scrollIntoView({block:'start',behavior:'smooth'})});
$('#demoReset').addEventListener('click',async()=>{LCNDemo.reset();active=null;deskBlank=false;previewPinned=false;previewTaskId='';previewMissionId='';selectedOpportunityId='';selectedTaskId='';filterAgent='ALL';filterStatus='ALL';filterQuery='';filterDate='';$('#taskSearch').value='';await load();showView('revenue');toast('Demo reset. All records are fictional and stay in this tab.')});
window.demoRefresh=()=>{
 document.querySelectorAll('[data-business-proof]').forEach(el=>el.remove());
 const invoiceDetail=$('#firstInvoiceDetail');if(invoiceDetail)invoiceDetail.textContent='Demo invoices stay synthetic. No real-client or real-payment KPI can be satisfied here.';
 const selected=(state.revenue?.opportunities||[]).find(o=>o.id===selectedOpportunityId),proposal=(state.revenue?.proposals||[]).find(p=>p.id===selected?.proposal_id);
 let hint='Try the Revenue workflow to evaluate a sample brief, review a proposal, and create a fictional invoice.';
 if(selected){if(selected.state==='NEW')hint='Next: open Opportunities & Proposals and choose EVALUATE LOCALLY.';else if(selected.state==='QUALIFIED')hint='Next: inspect the prepared fit and risk scores, then choose PURSUE.';else if(selected.state==='PURSUE')hint='Next: GENERATE PROPOSAL creates a fixed sample scope, timeline and estimate.';else if(proposal?.approval_state==='DRAFT')hint='Next: review the sample proposal, then APPROVE, DISAPPROVE or CREATE REVISION.';else if(proposal?.approval_state==='APPROVED')hint='Next: MARK SAMPLE SUBMITTED records the step without sending a message.';else if(proposal?.approval_state==='SUBMITTED')hint='Next: MARK SAMPLE WON, then record a sample contract and deposit to activate production.';else if(selected.state==='WON')hint='Next: record both sample contract and deposit, ACTIVATE SAMPLE PROJECT, then CONVERT TO PRODUCTION MISSION.';else if(['PRODUCTION','DELIVERED','PAID'].includes(selected.state))hint='Production: review the mission plan and sample lanes in Collaborative Preview. Revenue → Projects lets you create a draft invoice and record a fictional payment.'}
 const view=document.querySelector('.view.on')?.id;
 if(['preview','tasks'].includes(view))hint='Mission loop: approve the plan; lanes advance every few seconds and pause for visual review and final delivery. SEND BACK uses your revision note. STOP, RESUME, RESET and REJECT update the sample ledger.';
 $('#demoHint').textContent=hint;
 const p=(state.revenue?.final_packages||[]).find(p=>p.mission_id===previewMissionId);let download=$('#demoDownloadPackage');if(p&&!download){download=document.createElement('button');download.id='demoDownloadPackage';download.className='demo-download';download.textContent='DOWNLOAD SAMPLE HANDOFF';download.onclick=()=>LCNDemo.downloadPackage(p.id);reviewNote.after(download)}else if(!p&&download)download.remove();if(p&&download)download.onclick=()=>LCNDemo.downloadPackage(p.id);
 const label=$('#operatingProfile');if(label&&!label.innerHTML)label.innerHTML='<div><small>PUBLIC SIMULATION</small><h2>Eight named responsibility lanes. One sample mission.</h2><p>Every provider card below is a simulated role. No accounts, API keys, provider sessions or local file access are used.</p></div>';
};
document.querySelector('#revenueDetail').addEventListener('click',e=>{if(e.target.closest('a[href="#preview"]')){e.preventDefault();showView('preview')}});
window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(['command','revenue','tasks','calendar','ledger','preview','connections'].includes(view))showView(view)});
