'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const routes=['home','media','heart','command','diagnostics'],names={home:'HOME',media:'MEDIA',heart:'SYSTEM HEART',command:'COMMAND DECK',diagnostics:'DIAGNOSTICS'};
let current='home',trail=[],scenario='sample',playing=true,muted=false,position=154,volume=45,track=0,pendingAction=null,holding=false;
const choices=[['cpu','CPU temperature'],['gpu','GPU temperature'],['media','Media destination'],['heart','System Heart destination'],['diagnostics','Diagnostics destination'],['command','Command Deck destination'],['steam','Steam launcher'],['sleep','Sleep PC'],['wake','Wake on LAN'],['mute','Mute audio']];
const defaults=[{action:'cpu',label:'CPU TEMPERATURE'},{action:'media',label:'SPOTIFY / MEDIA'},{action:'steam',label:'STEAM CLIENT'},{action:'gpu',label:'GPU TEMPERATURE'},{action:'heart',label:'SYSTEM HEART'},{action:'mute',label:'AUDIO MUTE STATE'}];
let ports=defaults.map(x=>({...x}));try{const saved=JSON.parse(localStorage.getItem('ruca-public-v1-ports')||'null');if(Array.isArray(saved)&&saved.length===6&&saved.every(p=>choices.some(c=>c[0]===p.action)&&typeof p.label==='string'))ports=saved;}catch{}
function say(t){$('#feedback').textContent=t;}
function buttonize(el,label,fn){const b=document.createElement('button');for(const a of el.attributes)b.setAttribute(a.name,a.value);b.type='button';b.innerHTML=el.innerHTML;b.setAttribute('aria-label',label);b.addEventListener('click',fn);el.replaceWith(b);return b;}
$$('[data-name^="nav-item-"]').forEach(el=>{const route=el.dataset.name.slice(9).toLowerCase();buttonize(el,names[route],()=>show(route));});
$$('[data-name^="command-pod-port-"]').forEach(el=>{const n=Number(el.dataset.name.slice(-2))-1;const b=buttonize(el,'Port '+(n+1)+': '+ports[n].label,()=>{if(!holding)openPort(n);holding=false;});let timer;b.addEventListener('pointerdown',()=>{holding=false;timer=setTimeout(()=>{holding=true;configure(n);},550)});['pointerup','pointerleave','pointercancel'].forEach(t=>b.addEventListener(t,()=>clearTimeout(timer)));b.addEventListener('contextmenu',e=>{e.preventDefault();configure(n);});b.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();configure(n)}});});
const allText=$$('.screen-stage p');allText.forEach(p=>{p.textContent=p.textContent.trim();const t=p.textContent;const replace={'HOST LINK NOMINAL':'SAMPLE HOST / CONNECTED','LATENCY: 12ms':'ILLUSTRATIVE SESSION','SECURE SHELL v1.42.0':'V1 DESIGN / BROWSER DEMO','LIVE READ':'SAMPLE','REAL-TIME SYNCED':'SAMPLE DATA','REFRESH INTERVAL: 100ms':'ILLUSTRATIVE METRICS','INTEL CORE I9-14900K':'SAMPLE CPU','NVIDIA RTX 4090':'SAMPLE GPU','GPU FREQUENCY':'GPU TEMPERATURE','HEART RECOVERY FEED':'SYSTEM HEART','94%':'OPEN','HEART STATUS // 94% NOMINAL RATE':'MEASURED VALUES // OPEN SYSTEM HEART','192.168.1.144':'PUBLIC DEMO / NO PC LINK','v1.42.0-RELEASE':'DESIGN REFERENCE','WIFI 6E DIRECT':'SIMULATED CONNECTION','COMMANDS ARMED // TAP EXECUTED IMMEDIATELY':'DEMO ONLY // NO DESKTOP ACTIONS','KEYBOARD DISENGAGED // TAP SYSTEM FOR TRIGGER':'FILTER AND PREVIEW SUPPORTED ACTIONS'};if(replace[t])p.textContent=replace[t];if(t==='09:41:52 UTC')p.textContent='V1 / SEPTEMBER 2026';p.dataset.sample=p.textContent;});
// The native September source exposes CPU, GPU and memory. The remaining Figma tiles are design concepts.
const instrument=$('[data-name="instrument-grid-sections"]');if(instrument){let tiles=$$('p',instrument).filter(p=>p.textContent==='SAMPLE').map(p=>p.parentElement.parentElement);tiles.forEach((tile,i)=>{if(i>4){$$('p',tile).forEach(p=>{if(/^(2\.1 GB|842\.1 GB|1\.8 TB|12 ms|04:12:35|99\.8%|12\.1V)$/.test(p.textContent)){p.textContent='—';p.dataset.sample='—'}if(p.textContent==='SAMPLE'){p.textContent='UNAVAILABLE';p.dataset.sample='UNAVAILABLE'}});}});}
$$('#screen-heart p').forEach(p=>{if(/^(2\.1 GB|842\.1 GB|1\.8 TB|12 ms|04:12:35|99\.8%|12\.1V)$/.test(p.textContent)){p.textContent='—';p.dataset.sample='—'}});
$$('[data-name="system-heart"]').forEach(el=>buttonize(el,'Open System Heart',()=>show('heart')));
function fit(){const viewport=$('#viewport'),s=Math.min(viewport.clientWidth/2400,viewport.clientHeight/1080);$('#stage').style.transform=document.fullscreenElement?'translate(-50%,-50%) scale('+s+')':'scale('+s+')';}new ResizeObserver(fit).observe($('#viewport'));document.addEventListener('fullscreenchange',fit);
function show(route,push=true){if(!routes.includes(route))route='home';if(push&&route!==current)trail.push(current);current=route;$$('[data-route]').forEach(s=>s.classList.toggle('active',s.dataset.route===route));$$('[data-go]').forEach(b=>{if(b.dataset.go===route)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});history.replaceState(null,'','#'+route);$('#design-link').href='/assets/mobile-current/'+route+'.png';$('#design-image').src='/assets/mobile-current/'+route+'.png';$('#design-image').alt='Exact current '+names[route]+' Figma frame';$('#native-link').href='/assets/mobile-current/native-'+route+'-sep07.png';$('#native-image').src='/assets/mobile-current/native-'+route+'-sep07.png';$('#native-image').alt='Actual native Android '+names[route]+' validation capture, September 7';$('#interaction-help').textContent=route==='home'?'Tap a port to open it. Hold or configure a port to change its assignment.':route==='media'?'Try play/pause, previous, next, seek and volume. All playback is simulated.':route==='command'?'Filter commands and preview supported actions. Power commands ask for confirmation.':route==='heart'?'CPU, GPU and memory have native data support. Additional design tiles show unavailable.':'Inspect sample connection state and source identity. Switch scenarios to compare recovery states.';fit();}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#back').onclick=()=>show(trail.pop()||'home',false);window.addEventListener('hashchange',()=>show(location.hash.slice(1),false));$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#viewport').requestFullscreen()}catch{say('Use your browser zoom to enlarge this view.')}};
function updateState(){const status=scenario==='offline'?'UNAVAILABLE':scenario==='degraded'?'STALE':'ACTIVE';allText.forEach(p=>{const base=p.dataset.sample;if(!base)return;let value=base;if(scenario!=='sample'&&/^(47°C|62°C|68°C|24\.2%|81\.5%|12\.4 GB|2:34|4:12|45%|12ms \(NOMINAL\)|0\.00%|94% \/\/ POWER CONNECTED)$/.test(base))value=scenario==='offline'?'— / UNAVAILABLE':base+' / STALE';if(base==='SAMPLE HOST / CONNECTED')value='SAMPLE HOST / '+(scenario==='sample'?'CONNECTED':scenario==='degraded'?'DEGRADED':'DISCONNECTED');if(base==='ACTIVE')value=status;if(base==='SAMPLE')value=scenario==='sample'?'SAMPLE':status;if(base==='DESKTOP // ONLINE')value='DESKTOP // '+(scenario==='sample'?'SAMPLE CONNECTED':scenario==='degraded'?'SAMPLE DEGRADED':'SAMPLE OFFLINE');if(base==='CONTINUUM ENVIRONMENT DOMINANT'&&scenario!=='sample')value=scenario==='offline'?'NO CURRENT DESKTOP VALUES / ASSIGNMENTS RETAINED':'LAST VALUES RETAINED / FRESHNESS NEEDS ATTENTION';p.textContent=value;});$$('[data-name="intelligence-ribbon"] p').forEach(p=>p.textContent='PUBLIC DEMO // '+(scenario==='sample'?'CONNECTED SAMPLE // ILLUSTRATIVE DATA':scenario==='degraded'?'DEGRADED SAMPLE // VALUES STALE':'DISCONNECTED SAMPLE // NO TELEMETRY'));$$('[data-name="bottom-status"] p').forEach((p,i)=>{if(i%3===1)p.textContent='SAMPLE SESSION // '+status});renderPorts();renderMedia();}
$('#scenario').onchange=e=>{scenario=e.target.value;updateState();say(scenario==='sample'?'Connected sample restored. Values are illustrative.':scenario==='degraded'?'Degraded sample: last values stay visible and are marked stale.':'Disconnected sample: telemetry is unavailable and your port assignments remain.');};
function renderPorts(){$$('[data-name^="command-pod-port-"]').forEach(el=>{const n=Number(el.dataset.name.slice(-2))-1,p=ports[n],t=$$('p',el);if(t.length<4)return;t[1].textContent=['cpu','gpu'].includes(p.action)?'TELEMETRY':['media','heart','command','diagnostics'].includes(p.action)?'DESTINATION':'COMMAND';t[2].textContent=p.action==='cpu'?(scenario==='offline'?'—':scenario==='degraded'?'47°C / STALE':'47°C'):p.action==='gpu'?(scenario==='offline'?'—':scenario==='degraded'?'62°C / STALE':'62°C'):p.action==='mute'?(muted?'ON':'OFF'):p.action==='media'?'Spotify':p.action==='heart'?'OPEN':scenario==='offline'?'UNAVAILABLE':'READY';t[3].textContent=p.label;el.setAttribute('aria-label','Port '+(n+1)+': '+p.label+'. Hold or press F2 to configure');});}
function openPort(n){const p=ports[n];if(routes.includes(p.action)){show(p.action);return}if(['cpu','gpu'].includes(p.action)){show('heart');return}command(p.action);}
for(let n=0;n<6;n++)$('#port-number').add(new Option('Port '+String(n+1).padStart(2,'0'),n));choices.forEach(c=>$('#port-assignment').add(new Option(c[1],c[0])));
function fillPort(){const p=ports[Number($('#port-number').value)];$('#port-assignment').value=p.action;$('#port-label').value=p.label;}
function configure(n=0){$('#port-number').value=n;fillPort();$('#port-dialog').showModal();}
$('#configure').onclick=()=>configure();$('#port-number').onchange=fillPort;$('#port-assignment').onchange=()=>{$('#port-label').value=choices.find(c=>c[0]===$('#port-assignment').value)[1].toUpperCase()};$('#port-dialog').addEventListener('close',()=>{if($('#port-dialog').returnValue!=='save')return;const n=Number($('#port-number').value);ports[n]={action:$('#port-assignment').value,label:$('#port-label').value.trim()||'PERSONAL PORT'};try{localStorage.setItem('ruca-public-v1-ports',JSON.stringify(ports))}catch{}renderPorts();say('Port '+(n+1)+' saved in this browser: '+ports[n].label+'.');});
function command(action){if(action==='sleep'||action==='wake'){pendingAction=action;$('#action-title').textContent=action==='sleep'?'Sleep PC?':'Wake on LAN?';$('#action-description').textContent=action==='sleep'?'This previews the native confirmation flow. Confirming changes only this demo to its disconnected state.':'This previews a wake request. The native app sends a LAN packet; sending alone does not prove the desktop woke. This demo sends no packet.';$('#action-dialog').showModal();return}if(scenario==='offline'){say('Sample desktop unavailable. Reconnect using the scenario selector; assignments are retained.');return}if(action==='mute'){muted=!muted;renderPorts();renderMedia();say('Sample audio '+(muted?'muted':'unmuted')+'.');return}if(action==='play'){playing=!playing;renderMedia();say('Sample playback '+(playing?'playing':'paused')+'.');return}if(action==='next'||action==='previous'){track=(track+(action==='next'?1:2))%3;position=0;renderMedia();say('Selected sample track '+(track+1)+'.');return}if(action==='volume'){volume=Math.min(100,volume+5);renderMedia();say('Sample volume '+volume+'%.');return}say('Sample launcher request: '+action.toUpperCase()+'. No desktop application is launched.');}
$('#action-dialog').addEventListener('close',()=>{if($('#action-dialog').returnValue!=='confirm')return;if(pendingAction==='sleep'){scenario='offline';$('#scenario').value=scenario;updateState();say('Sleep confirmed in demo. Sample desktop disconnected.')}else{say('Wake request simulated. Delivery does not prove wake; use Connected sample to preview recovery.')}});
const transport={'btn-prev':'previous','btn-next':'next','btn-play-pause':'play'};Object.entries(transport).forEach(([id,action])=>buttonize($('[data-name="'+id+'"]'),action==='play'?'Play or pause sample':action+' sample track',()=>command(action)));['back','forward'].forEach(direction=>buttonize($('[data-name="btn-skip-'+direction+'-10"]'),'Seek '+direction+' ten seconds',()=>{if(scenario==='offline'){say('Playback unavailable in disconnected sample.');return}position=Math.max(0,Math.min(252,position+(direction==='back'?-10:10)));renderMedia();say('Sample position '+time(position)+'.')}));
function time(n){return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
const seek=$('[data-name="seek-track"]'),seekRange=document.createElement('input');seekRange.type='range';seekRange.min=0;seekRange.max=252;seekRange.value=position;seekRange.className='range-control';seekRange.setAttribute('aria-label','Sample playback position');seek.replaceWith(seekRange);seekRange.oninput=e=>{position=Number(e.target.value);renderMedia()};
const volumeTrack=$('[data-name="volume-track"]'),volumeRange=document.createElement('input');volumeRange.type='range';volumeRange.min=0;volumeRange.max=100;volumeRange.value=volume;volumeRange.className='range-control';volumeRange.setAttribute('aria-label','Sample volume');volumeTrack.replaceWith(volumeRange);volumeRange.oninput=e=>{volume=Number(e.target.value);renderMedia()};
function renderMedia(){const hud=$$('[data-name="now-playing-hud"] p');hud[0].textContent=scenario==='offline'?'PLAYBACK UNAVAILABLE':scenario==='degraded'?'STALE SAMPLE PLAYBACK':playing?'SAMPLE / PLAYING':'SAMPLE / PAUSED';hud[1].textContent=['Nebula Dreams','Stellar Passage','Quiet Orbit'][track];hud[2].textContent='Illustrative track metadata / no audio stream';seekRange.value=position;seekRange.disabled=scenario==='offline';volumeRange.disabled=scenario==='offline';volumeRange.value=volume;const times=$$('[data-name="seek-container"] p');if(times[0])times[0].textContent=scenario==='offline'?'—':time(position);if(times[1])times[1].textContent=scenario==='offline'?'—':'4:12';const v=$$('[data-name="volume-panel"] p').find(p=>/%/.test(p.textContent));if(v)v.textContent=muted?'MUTED':volume+'%';$('[data-name="btn-play-pause"]').setAttribute('aria-pressed',String(playing));}
const commandMap={'SLEEP PC':'sleep','WAKE ON LAN':'wake','PLAY / PAUSE':'play','SKIP FORWARD':'next','VOLUME UP (+5%)':'volume','AUDIO MUTE STATE':'mute'};
const commandTexts=$$('#screen-command p');commandTexts.filter(p=>Object.keys(commandMap).includes(p.textContent)||['LOCK HOST','RESTART EXECUTION','BRIGHTNESS UP','BRIGHTNESS DOWN','MATRIX TEST COLOR','TOGGLE HUD PROJECTION'].includes(p.textContent)).forEach(p=>{const label=p.textContent,action=commandMap[label],row=p.parentElement,b=buttonize(row,label,()=>action?command(action):say(label+' is a Figma design concept and is not implemented in the native V1 source.'));b.classList.add('command-button');b.dataset.commandLabel=label;const last=$$('p',b).at(-1);last.textContent=action?'PREVIEW':'DESIGN ONLY';if(!action)b.setAttribute('aria-disabled','true');});
const filter=commandTexts.find(p=>p.textContent==='FILTER COMMANDS...'),input=document.createElement('input');input.type='search';input.className='command-search';input.placeholder='FILTER COMMANDS...';input.setAttribute('aria-label','Filter commands');filter.replaceWith(input);input.oninput=()=>$$('.command-button').forEach(b=>b.hidden=!b.dataset.commandLabel.toLowerCase().includes(input.value.toLowerCase()));
updateState();show(location.hash.slice(1)||'home',false);
